apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo-node
  template:
    metadata:
      labels:
        app: mongo-node
    spec:
      containers:
      - name: mongo-node
        image: alien777/mongo-node:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mi-node-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 3000
  selector:
    app: mongo-node